[package]
name = "rust_lib_baby_monitoring_app"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
anyhow = "1.0.93"
csv = "1.3.1"
flutter_rust_bridge = "=2.6.0"
rayon = "1.10.0"
thiserror = "2.0.3"
chrono = "0.4"
